### ISSUE TITLE
[Bug]: Massive FPS drops beim scoreboard

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#1]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Man hat sehr wenige fps wenn man im scoreboard ist 
<img width="930" alt="image" src="https://github.com/user-attachments/assets/2cac4320-c5db-460a-adbf-3b7d63def371">

**Comment by copyandexecute** [comment]
wird im nächsten update rausgeworfen, schreib obs dann gefixed wurde
