### ISSUE TITLE
[Bug]: Train Bug

### ISSUE THREAD

**Issue by TigerCrafter** [HGLabor/issues#14]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

![image](https://github.com/user-attachments/assets/b7173d05-3a5b-4cd7-9ce4-b00c5e199146)
Man kann hier nicht auf den Zug links gehen. Man muss springen, sonst zählt es so, wie wenn man gegen eine Wand von der Seite läuft.

**Comment by RadFlunder** [comment]
@TigerCrafter Das müsste ja auch von dem Block kommen, oder? Weil dann kann man das Issue ja schließen

**Comment by TigerCrafter** [comment]
> @TigerCrafter Das müsste ja auch von dem Block kommen, oder? Weil dann kann man das Issue ja schließen

Stimmt
