### ISSUE TITLE
[Feature]: Disable InvMove Mod when playing

### ISSUE THREAD

**Issue by TigerCrafter** [HGLabor/issues#18]
### Beschreibung

Hat was mit #6 zu tun. Wäre aber echt besser, wenn die deaktiviert werden würde. Oder ein System um die Runs vom Leaderboard im nachhinein noch anschauen zu können

**Comment by TigerCrafter** [comment]
Mit der Mod kann man fliegen, wenn man von der SubwaySurfers-Map runter geht und die Leertaste spammt

**Comment by copyandexecute** [comment]
Ich schaus mir an danke (Mod Heißt inventory move ) oder so für mich

**Comment by copyandexecute** [comment]
Hab versucht es zu fixen, kommt mit dem nächsten update
