### ISSUE TITLE
[Bug]: Nametag zu groß

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#2]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Die Nametags sind zu groß
<img width="592" alt="image" src="https://github.com/user-attachments/assets/ebfc56bf-8d29-40f2-a154-8d491025cb12">

**Comment by copyandexecute** [comment]
ist das in vanilla auch so?

**Comment by copyandexecute** [comment]
ich fix es aber mache es nur für subwaysurfers

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/337e5a92-e805-4d47-8ba1-8c8141fb6e90)
passt fürs erste
