### ISSUE TITLE
[Bug]: Subwaysurfers controller bug

### ISSUE THREAD

**Issue by izukey** [HGLabor/issues#20]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Wenn man mit controller subwaysurfers spielt kann man sich frei bewegen 

https://github.com/user-attachments/assets/186f5bf4-e523-456d-a32c-fa0130f572c5

**Comment by izukey** [comment]
ist vom ding her das gleiche wie #18 und #6

**Comment by TigerCrafter** [comment]
Kann man mit dem Controller auch fliegen wenn man Jump spammt, während man außerhalb von der Map ist?

**Comment by izukey** [comment]
ja kann man

**Comment by izukey** [comment]
https://github.com/user-attachments/assets/2a24f47d-c79c-4a3e-8f68-b55fc3b32f6e

**Comment by copyandexecute** [comment]
lol danke fürs reporten

**Comment by copyandexecute** [comment]
wie heißt die controller mod oder ist das von mc?

**Comment by copyandexecute** [comment]
Ok hab versucht es zu fixen, kommt mit dem nächsten update
