### ISSUE TITLE
Profiles switcher in client options crashed das spiel

### ISSUE THREAD

**Issue by 0hAlex** [HGLabor/issues#20]
Profiles sind komplett verbuggt und gehen absolut nicht, wenn man ein drittes machen will passierte bei mir erst nichts und dann habe ich alle profiles gelöscht und mien game ist gecrashed xd 
https://mclo.gs/RdDKAlY
![Screenshot 2023-06-03 133647](https://github.com/HGLabor/issues/assets/85081415/a82572d6-b80b-415e-ae12-7c47bf437bf9)

**Comment by 0hAlex** [comment]
Das ist jetzt schade jungs

![Screenshot 2023-06-03 133901](https://github.com/HGLabor/issues/assets/85081415/e86d9315-7f92-4975-a9b8-3394f770933d)

**Comment by mooziii** [comment]
hat nix mit einander zu tun?

**Comment by 0hAlex** [comment]
issue ist fixed

**Comment by enricoxD** [comment]
Gibt's irgendwie mehr Infos dazu? Konnte das bisher nicht reproduzieren

**Comment by 0hAlex** [comment]
> Gibt's irgendwie mehr Infos dazu? Konnte das bisher nicht reproduzieren

Wie gesagt mittlerweile geht es eig seit der neuen UI nur Mooz scheint damit noch iwas zu haben.

**Comment by enricoxD** [comment]
> UI Crash einfach random (ungezogen auf Profile Switcher) mit extrem komischen Exit Code (-23131242). Beispiel: #4 

Passiert das wenn du das dropdown ding öffnest oder wenn du das Profil wechselst?
