### ISSUE TITLE
Prefix Text Coords

### ISSUE THREAD

**Issue by 0hAlex** [HGLabor/issues#22]
Prefix Text bei den Coords buggt sehr wenn man es ausschaltet (xyz anzeige wird ausgeschaltet und der prefix text moved nach hinten)
![2023-06-05_10 41 52](https://github.com/HGLabor/issues/assets/85081415/b8e1b534-ff7c-4d75-84db-9d92952d6aef)

(btw time hat immer noch keinen prefix text aber die option diesen auszustellen)

**Comment by mooziii** [comment]
Fixed in next version
