### ISSUE TITLE
[Bug]: Hitbox wird nicht kleiner, wenn der Jump mit der Rolle gecancelt wird

### ISSUE THREAD

**Issue by Kolpixx** [HGLabor/issues#22]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Beim Rollen wird halt die Hitbox kleiner, aber wenn man springt und den Sprung dann mit einer Rolle cancelt, dann bleibt die Hitbox weiterhin groß. Kann vorallem nervig werden, wenn man schnell ist.

Video: https://youtu.be/noxZfYhcSnU?t=20

**Comment by copyandexecute** [comment]
wird mit dem neuen update kommen
