### ISSUE TITLE
[Bug]: Subway Surfers Coin Counter UI

### ISSUE THREAD

**Issue by hennycraft52** [HGLabor/issues#25]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Es gibt einen Bug wenn der Spieler in Subway Surfers Münzen einsammelt. Der Münzen Count in der UI verändert sich nicht.

**Comment by hennycraft52** [comment]
![Screenshot 2024-08-29 161728](https://github.com/user-attachments/assets/87d55143-65c2-4212-9efb-b4d2d44cab73)
Hier noch ein Screenshot

**Comment by MeisterAH** [comment]
oh dachte das wäre
fixed gibt aber auch schon issue dafür https://github.com/HGLabor/issues/issues/9

**Comment by hennycraft52** [comment]
Sry. Soll ich dann hier close?

**Comment by MeisterAH** [comment]
jo kannst du machen alles gut ^^
