### ISSUE TITLE
[Bug]: Items funktionieren nicht

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#3]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Wenn man Items aufsammelt geben sie keinen effect / haben keinen nutzen

**Comment by copyandexecute** [comment]
true, es wird nicht angezeigt aber den effekt hat man trotzdem oder?
welches item hast du aufgehoben

**Comment by copyandexecute** [comment]
als ich hoverboard hatte, ahtte ich es nicht visuell aber die funktion ging trotzden

**Comment by MeisterAH** [comment]
jaa aber bei jedem anderem Item außer das Hoverboard hat gar nichts funktioniert

**Comment by copyandexecute** [comment]
bin dran thx

**Comment by copyandexecute** [comment]
ist irgendwie fixed? wenn nicht mal nochmal auf
