### ISSUE TITLE
[Bug]: loch am anfang --> in block glitchen auf dach --> infinite score

### ISSUE THREAD

**Issue by SecretBot155** [HGLabor/issues#34]
### Welcher Client wurde verwendet?

Unbekannt

### Beschreibung

ich kann es gerade leider nicht reproduzieren scheint irgendwie random zu sein aber manchmal ist am anfang ein großes loch (schon bekannt glaub ich) und dann kann man rechts sich in einen block des dachs glitchen und unendlich score bekommen

**Comment by copyandexecute** [comment]
wird mit dem nächsten update gefixed sein! also nicht das loch aber dass player.y < start.Y = gamestop

**Comment by SecretBot155** [comment]
ich glaub ich weiß jetzt wie man reproducen kann, irgendwei wenn man die ganze zeit sneaken spammt und dann stirbt und direkt auf retry dann passiert das manchmal
