### ISSUE TITLE
[Bug]: Glitchen in Züge und Fallen Zwischen Züge/Grüne Rampe

### ISSUE THREAD

**Issue by bifaciall** [HGLabor/issues#42]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Wenn man Seitlich zwischen Zügen switcht kann es teilweise dazu kommen das man in den Zug fällt auf den man hin möchte.
![SCR-20240902-sav](https://github.com/user-attachments/assets/b864e2d9-9ac2-4636-a60e-aaa927d24b4d)
![SCR-20240902-sal](https://github.com/user-attachments/assets/206a90a3-6107-4d3c-9cd6-978972c77271)
![SCR-20240902-s7l](https://github.com/user-attachments/assets/e4255102-34ee-44e6-84c3-0c6e079a280e)
![SCR-20240902-s79](https://github.com/user-attachments/assets/68f79b97-95bc-499a-ab22-13017ed1239f)
Die ersten Zwei Bilder sind von dem 2. Typ, in dem Fall: Fallen zwischen Zug und grüner Rampe.
Die letzen Zwei sind vom Wechseln zu einer anderen Bahn auf einem Zug zu einem anderen Zug, wobei man in den neuen Zug, zu dem man wechselt glitcht.
Bilder 1 und 3 sind jeweils die Todesgründe und die Mapabschnitte wo dies auftritt.
Meiner Vermutung nach liegt es aber wahrscheinlich eher an den Hitboxen, worauf Norisk ja auch in seinem Video eingegangen ist.

**Comment by bifaciall** [comment]
Durch geschicktes Wechseln der Lanes auf einer Rampe ist es einem möglich durch den angrenzenden Zug zu laufen und danach normal weiterspielen zu können: 

https://github.com/user-attachments/assets/582c64a3-d7d7-4202-9eab-c9c1194857e3

**Comment by TigerCrafter** [comment]
@RadFlunder kannst du auch schließen. Ist auch wegen dem Block
