### ISSUE TITLE
[Bug]: Subway surfers startet falsch

### ISSUE THREAD

**Issue by Lood319** [HGLabor/issues#49]
### Welcher Client wurde verwendet?

Vanilla

### Beschreibung

Jedesmal wenn ich Subway surfers starte spawne ich auf einen Bedrock block und sobald ich gehe falle ich runter und es  ercheint `GAME OVER` im chat
![Screenshot (291)](https://github.com/user-attachments/assets/ea99e753-50bf-482c-bcc6-2898846b73e7)
Das war jetzt Badlion client (der screenshot) aber wenn ich normal über minecraft launcher starte stürzt der server nach ungefähr 5 Sekunde sofort ab.

**Comment by Lood319** [comment]
![image](https://github.com/user-attachments/assets/8c5bdcbf-fde7-4155-81fa-93fad37f4e4a)
ohne dieses badlion UI

**Comment by Lood319** [comment]
![image](https://github.com/user-attachments/assets/894fdfd8-450c-4897-a43f-8d3575474b4b)
![image](https://github.com/user-attachments/assets/d426bbb5-72be-4a00-a436-0e6c4ebadf87)
generell funktioniert bei mir irgendwie gar nichts

**Comment by SecretBot155** [comment]
Du musst dazu den Norisk Client verwenden, wenn du zurzeit noch nicht auf der Whitelist dafür stehst, musst du dich allerdings noch ein bisschen gedulden.
@Lood319
