### ISSUE TITLE
[Bug]: Arrow keys doesn't work anymore

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#5]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Man kann nicht mehr mit arrow keys spielen

**Comment by TigerCrafter** [comment]
Man konnte nie mit Arrow Keys spielen

**Comment by MeisterAH** [comment]
fr?

**Comment by TigerCrafter** [comment]
> fr?

Ja
