### ISSUE TITLE
NPCs werden in der Tablist angezeigt

### ISSUE THREAD

**Issue by BlueSneakers** [HGLabor/issues#5]
Auf Servern wie Hypixel oder GommeHD werden NPCs in der Tablist angezeigt.
![2023-05-19_23 13 00](https://github.com/HGLabor/issues/assets/76217953/c9caa021-6a53-47a0-b39f-9e959a892108)
![2023-05-19_23 21 19](https://github.com/HGLabor/issues/assets/76217953/8d4f72a7-5a2f-4d2b-ba5f-16241794e3cc)

**Comment by mooziii** [comment]
ist normal, verschwinden nach einziger Zeit wieder -> server issue 
![img](https://i.imgur.com/RXzk0Xr.jpeg)
However, we could add an "Hide Invalids" option to TabEditor which hides invalid entries completely.

**Comment by mooziii** [comment]
Added a Remove NPCs option.
