### ISSUE TITLE
[Bug]: Random death

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#56]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Man stirbt manchmal einf instant wenn man auf spielen klickt 
reason:
<img width="744" alt="image" src="https://github.com/user-attachments/assets/7e15ff7c-77b7-4b41-89ed-24f5a156c252">

**Comment by TigerCrafter** [comment]
Vielleicht macht deine Maus einen Double Klick (passiert bei mir auch manchmal), dadurch wird /subwaysurfers start zweimal ausgeführt, was dann zählt wie /subwaysurfers stop.

**Comment by MeisterAH** [comment]
muss ich mir mal nochmal anschauen
