### ISSUE TITLE
[Bug]: No barriers 

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#6]
### Welcher Client wurde verwendet?
NoRiskClient

### Beschreibung

Wenn man sich im esc drück und dann sich bewegt während man im esc menu ist kann man sich frei bewegen

**Comment by MeisterAH** [comment]
ahh nvm is ja gar nicht vanilla das man sich im esc screen bewegen kann

**Comment by MeisterAH** [comment]
jaa wär dann halt cheaten

**Comment by copyandexecute** [comment]
Man läuft doch weiter?

**Comment by MeisterAH** [comment]
nah man kann sich einf frei rumbewegen von der subway surfer map runterlaufen etc. Die Mod heißt glaube ich inventory move oderso
