### ISSUE TITLE
Keystrokes Background

### ISSUE THREAD

**Issue by BlueSneakers** [HGLabor/issues#6]
Der Background der Keystrokes kann nicht deaktiviert werden.

**Comment by mooziii** [comment]
Wie stellst du es dir ohne Background vor?

**Comment by BlueSneakers** [comment]
Wie bei fps oder ping, dass nur der Text angezeigt wird. Wozu ist der Button sonst da?

**Comment by mooziii** [comment]
Hm sieht halt weird aus wenn da einfach buchstaben rumschweben oder?
Die Option ist da weil BasicHud alle common optionen wie rgb enthält und dazu gehört halt auch background..

**Comment by BlueSneakers** [comment]
ka

**Comment by mooziii** [comment]
Implemented in 0.0.6
