### ISSUE TITLE
[Bug]: Zwischen zwei Züge geglitched

### ISSUE THREAD

**Issue by Blitz878787** [HGLabor/issues#60]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Es gibt einen Bug wenn man zwischen zwei Zügen crouched und eine drehung macht. Ich habe keine Ahnung wieso eigentlich geht das von den hitboxen ja nicht. Das war am 6 September um 20:~~ Uhr.
![2024-09-06_20 27 13](https://github.com/user-attachments/assets/630e040a-3497-4323-bd00-278bb52d26e9)

**Comment by TigerCrafter** [comment]
@RadFlunder ist wahrscheinlich auch wegen dem Block. Kannst du schließen.

**Comment by RadFlunder** [comment]
Sicher? Seine Beschreibung hört sich irgendwie anders an... oder bin ich nur wieder dumm @TigerCrafter

**Comment by TigerCrafter** [comment]
> Sicher? Seine Beschreibung hört sich irgendwie anders an... oder bin ich nur wieder dumm @TigerCrafter 

Ja ziemlich sicher. Es ist ja das gleiche wie hier: https://github.com/HGLabor/issues/issues/42#issuecomment-2325257020

**Comment by RadFlunder** [comment]
Ich close es jetzt erstmal und wenn der Kollege was anderes gemeint hat wird er sich ja melden. @TigerCrafter @Blitz878787
