### ISSUE TITLE
[Feature]: Disable Subwaysurfers shader

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#62]
### Beschreibung

Durch den Subway Surfers Shader lädt bei mir die Welt nicht richtig. Deshalb wäre es nice, wenn man ihn deaktivieren könnte.

**Comment by TigerCrafter** [comment]
Hat glaube ich was mit #59 zu tun

**Comment by TigerCrafter** [comment]
Man kann ihn deaktivieren. Drücke einfach den Keybind um Shader zu deaktivieren (Standart:K)

**Comment by MeisterAH** [comment]
jo danke dir
