### ISSUE TITLE
[Bug]: HGLabor SUbwaysurfers buggt

### ISSUE THREAD

**Issue by EmrageGHC** [HGLabor/issues#63]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Es gibt einen Bug wenn ich in SUbwaysurfers reinwill. Dann komm ich nicht rein
![Bild_2024-09-08_105354944](https://github.com/user-attachments/assets/844506c4-6082-4be4-8034-3a8535693b11)

**Comment by MeisterAH** [comment]
https://github.com/HGLabor/issues/issues/56 ^^
