### ISSUE TITLE
[Bug]: Fliegende coins in der Luft 

### ISSUE THREAD

**Issue by Blitz878787** [HGLabor/issues#64]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Ich habe einfach normal Subwaysurfers gespielt und dann ist das passiert. 
![2024-09-08_16 20 39](https://github.com/user-attachments/assets/e42fa0c1-5776-4232-8cae-fdff919c39da)
![2024-09-08_16 20 33](https://github.com/user-attachments/assets/f7c68ba2-46d4-463c-8eb1-f321195b95b0)

**Comment by MeisterAH** [comment]
https://github.com/HGLabor/issues/issues/58 ^^
