### ISSUE TITLE
[Bug]: Subways Surfer Hitbox

### ISSUE THREAD

**Issue by fischboy1337** [HGLabor/issues#65]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

Wenn man versucht auf einem Zug auf einem Container ruf lauf ding switch nach dem das schon geendet ist, glicht man nach unten.

https://github.com/user-attachments/assets/c91c1e70-9deb-40f2-97fe-637f4d750584

**Comment by TigerCrafter** [comment]
@copyandexecute kann es sein dass du vergessen hast, die Hitbox der Rampen zu verlängern?

**Comment by TigerCrafter** [comment]
@copyandexecute Die Rampen bestehen ja aus Barrier Blöcken. Du könntest vielleicht noch einen Barrier Block weiter nach hinten machen, das kein zu großes Loch zwischen Zug Hitbox Anfang und Rampen Ende ist.

**Comment by RadFlunder** [comment]
@TigerCrafter  Ich hab jetzt die Air blöcke durch oak slabs und planks ersetzt und die gehen definitiv weit genug über die Rampe, dass es umöglich ist sich da mehr reinzubuggen. Also würd ich sagen,dass das gefixt ist.

**Comment by RadFlunder** [comment]
**Fixed Bug:** HGLabor/subwaysurfers#57
