### ISSUE TITLE
[Bug]: In Blöcke buggen (basically infinite score glitch)

### ISSUE THREAD

**Issue by Kolpixx** [HGLabor/issues#66]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

https://youtu.be/Zj5uAprawEA?t=33

sehr einfach reproduzierbar

**Comment by hennycraft52** [comment]
Sollte eigentlich fixed sein :)

**Comment by Kolpixx** [comment]
> Sollte eigentlich fixed sein :)

Funktioniert immer noch:
https://youtu.be/8LoJJVMONGA?t=22

**Comment by Kolpixx** [comment]
@hennycraft52

**Comment by hennycraft52** [comment]
uh in dem local Projekt nd :(
