### ISSUE TITLE
Keystrokes Placement

### ISSUE THREAD

**Issue by BlueSneakers** [HGLabor/issues#7]
Sind die Keystrokes bereits aktiviert und werden diese verschoben, so wird diese „Verschiebung“ nicht gespeichert. Also nach einem Neustart des Clients sind die Keystrokes auf dem alten Platz. Werden die Keystrokes nach dem „Verschieben“ aus- und eingeschaltet, wird die „Verschiebung“ jedoch gespeichert.

**Comment by mooziii** [comment]
Fixed in next version
