### ISSUE TITLE
[Bug]: gap between trains

### ISSUE THREAD

**Issue by MeisterAH** [HGLabor/issues#8]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

wenn man sneak während man grad in einer lücke zwischen denn zügen ist stirbt man

**Comment by MeisterAH** [comment]
ist bei jeder map so

**Comment by copyandexecute** [comment]
bin dran danke fürs reporten

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/17018e8c-4fa9-4e7b-9d45-221fef9d2a57)
alt

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/566e26cc-beff-4efd-b423-a3292f8495eb)
Ich fixe es so dass die züge nach hinten eine länger hitbox haben

**Comment by copyandexecute** [comment]
Ansonsten muss

**Comment by copyandexecute** [comment]
Aber man muss natürlich auch die maps anpassen
