### ISSUE TITLE
Updater runs while Launcher is open

### ISSUE THREAD

**Issue by Krxwallo** [HGLabor/issues#8]
**Describe the bug**
The Launcher Updater can be run while the Launcher is already open. This can cause corruption of the launcher files.

**To Reproduce**
1. Open the Launcher
2. Wait for an update
3. Open another Launcher for updating
4. Wait while the Launcher happily installs the update

**Expected behavior**
The Launcher Updater should ask the user to first close the already running launcher.

**Comment by mooziii** [comment]
Yeah I understand, we need some sort of lock-file to prevent having multiple launcher instances open at the same time. If we add something like this, we should be aware for launcher crashes that may influence this

**Comment by mooziii** [comment]
The launcher now displays a warning to close all other instances before editing the installation files.
