### ISSUE TITLE
[Bug]: Fehlendes Power Icon bei SubWay Surfer wenn "Armor Display" an

### ISSUE THREAD

**Issue by MaNameisNick** [HGLabor/issues#84]
### Welcher Client wurde verwendet?

NoRiskClient

### Beschreibung

![2024-11-04_20 43 53](https://github.com/user-attachments/assets/104c6405-66fd-44b1-aef8-229d58b3c4f7)

Wenn man "Display Armor" an hat und in Subway Surfer das Boarditem einsammelt, wird einfach nur eine fehlende Tuxture links angezeigt :)
Ich hoffe das hat hier noch niemand gepostet hat, wenn doch tut es mir leid dass ich es doppelt poste D:
(Ich selbst konnte zumind. noch keinen solchen Bugreport hier auf GitHub finden)

**Comment by RadFlunder** [comment]
Hiii, danke für deinen Report^^! Es ist gecodet, aber wird noch eine Weile dauern bis es ins game kommt. Aktuell hat der Client halt prio

**Comment by RadFlunder** [comment]
![image](https://github.com/user-attachments/assets/7f184b2b-3de0-4c3a-bf8d-804d2f533de3)
das item sieht übrigens so aus.

**Comment by hennycraft52** [comment]
> Hiii, danke für deinen Report^^! Es ist gecodet, aber wird noch eine Weile dauern bis es ins game kommt. Aktuell hat der Client halt prio

also kann ich closen?
