### ISSUE TITLE
[Bug]: durch blöcke sehen

### ISSUE THREAD

**Issue by einfachnyxxo** [HGLabor/issues#89]
### Welcher Client wurde verwendet?

Unbekannt

### Beschreibung

![image](https://github.com/user-attachments/assets/d02f27ed-5b59-4667-bbed-c0208863107c)
![image](https://github.com/user-attachments/assets/0cb03a08-6887-4932-bb45-13850ea3327b)

man kann durch die bläcke schauen

**Comment by TigerCrafter** [comment]
Hat nichts mit SubwaySurfers oder HGLabor zu tun. Liegt einfach daran, das Block Entities aus einer bestimmten Distance nichtmehr gerendert werden

**Comment by hennycraft52** [comment]
Also kann ich closen oder @TigerCrafter

**Comment by TigerCrafter** [comment]
> Also kann ich closen oder @TigerCrafter 
> 

Jo
