### ISSUE TITLE
Launcher installs forge mods (bug)

### ISSUE THREAD

**Issue by mooziii** [HGLabor/issues#9]
**Describe the bug**
The client installs the forge versions of some mods.

**To Reproduce**
1. Search for a forge mod
2. Install

**Expected behavior**
Only fabric mods should be installed

**Screenshots**

**System (please complete the following information):**
 - OS: windows 11
 - Graphics Card: amd

**I read and understood the following:**
[x] I'm running the *latest* version of the noriskclient. Issues for older versions will be closed immediately. 
[x] I checked that this bug-report is unique.

frech wie ich bin assigne ich das jetzt einfach an kenny viel spaß damit @Krxwallo

**Comment by Krxwallo** [comment]
Can you give me an example for a forge mod/version that is falsely installed when searched for in the launcher? Looking at the code I can't see why forge mods would be installed.

**Comment by mooziii** [comment]
A mod that has support for both fabric and forge. For example: https://modrinth.com/mod/xaeros-world-map

**Comment by mooziii** [comment]
I assume it doesn't check for fabric support on the versions

**Comment by Krxwallo** [comment]
Xaero's World Map works fine on my end. It installs the correct fabric version as well as the correct fabric versions of the dependencies.

**Comment by mooziii** [comment]
ok nvm I'm dumb. It works fine I was just verwundert because it installed an dependency called "Forge Config API Port"
